name: Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: Run Super-Linter
    #   uses: github/super-linter@v4
    #   env:
    #     DEFAULT_BRANCH: main
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      working-directory: ./backend  
      run: npm install

    - name: Build the project
      working-directory: ./backend  
      run: npm run build

    - name: Run tests
      working-directory: ./backend  
      run: npm test

